### ISSUE TITLE
[CoE Starter Kit - BUG] Developer Compliance Centre app - Not found segment 'annotations'

### ISSUE THREAD

**Issue by MartinWhiteDAZN** [microsoft/coe-starter-kit#1026]
### Describe the issue

I am deploying the CoE in **Teams** and have hit an error when using the Developer Compliance Centre app. (Note this doesn't happen with the Production dataverse).

![image](https://user-images.githubusercontent.com/57627519/129333225-6c5de41e-f285-4997-91a1-b113b2d45358.png)

Having done some debugging it looks like the table "PowerApps App" needs to have attachments enabled, but this feature is not available in Teams dataverse (as far as I can see).

Using Monitor I found the error is in getAttachments...
![image](https://user-images.githubusercontent.com/57627519/129333632-c9eade12-dfed-44cf-93bb-84ccf8134966.png)
![image](https://user-images.githubusercontent.com/57627519/129333671-b362ca9e-6ab1-4338-99b7-222bb05cbfde.png)
![image](https://user-images.githubusercontent.com/57627519/129333693-42227e11-bf00-4ed8-9982-cdc68a524140.png)
![image](https://user-images.githubusercontent.com/57627519/129333706-24cde341-d7cd-4a38-89fb-1fa1d81b0cc6.png)

And in the app itself it shows the attachments field doesn't exist...
![image](https://user-images.githubusercontent.com/57627519/129333882-23cc8118-13b4-4d67-807f-5ad053009fc0.png)

Have I made a mistake deploying it, or is there an issue with the Teams version?

I did experience an issue yesterday relating to this ticket: 
https://github.com/microsoft/coe-starter-kit/issues/1012

So I am using version 2.3 of the Core Components and version 2.0 of the Governance components.

### Expected Behavior

App doesn't show an error when opening.

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.0

### What app or flow are you having the issue with?

Developer Compliance Centre app

### Steps To Reproduce

When an email is received from the flow 'Admin | Compliance detail request [Teams] v3' asking the user to open the Developer Compliance Centre app, the users clickes the link.
When the app opens it displays the error message.

![image](https://user-images.githubusercontent.com/57627519/129335021-af58b93a-366e-4ec4-af39-08d17592268a.png)

**Comment by manuelap-msft** [comment]
Hello,

thanks for letting us know - this is a bug in the Teams version, I'm able to repo. You are right that Attachments aren't available in Dataverse for Teams, we will have to make updates to this app to fix this bug and not use the Attachments field. 

Thank you,
Manuela

**Comment by mikefactorial** [comment]
@MartinWhiteDAZN This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by jukkan** [comment]
I'm still seeing this _"Resource not found for the segment 'annotations'"_ error in the December release for Developer Compliance Center app in a Dataverse for Teams environment. No unmanaged layers for the Canvas app. What could be the reason why Governance Components 2.9 app version still refers to attachments?

**Comment by manuelap-msft** [comment]
Reopening so we can investigate this.

**Comment by manuelap-msft** [comment]
Unfortuantely the only way to fix this is to create a duplicate of the Developer Compliance Center that doesn't refer to the Attachments field of the PowerApps App table.

Attachments are not available in Dataverse for Teams, but we have historically used them for makers to upload user manuals, FAQs or mitigation plans in this app so we can't remove this field completely as it would break existing usage.

The January release will contain a Developer Compliance Center (Teams Version) where the form doesn't allow you to upload attachments. The current plan is to stick with one Governance components solution and have two versions of this app in it. 
![image](https://user-images.githubusercontent.com/55705669/146376033-f037f6a0-5a75-464c-832c-a01ec5833bea.png)

We may consider using the new File field type going forward but have to plan this carefully to not cause a breaking change. 

Thank you for your patience as we fix this,
Manuela

**Comment by MartinWhiteDAZN** [comment]
Hi Manuela,
The October release removed the attachment field as that was preventing anyone from submitting the form.

When I tested it about a month ago I thought it the sharing was working.

I will try making a copy of DCC and strip out components to see if I can get it to share.

Kind Regards

***@***.***
Martin White
Office 365 Development Manager
***@***.******@***.***>
Hanover House, Feltham, London, TW13 7BZ

For support with building SharePoint pages please raise a ticket here: Office 365 Help<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=787250db374e5b0020a0532e53990eaa>
For Office 365 process requests please raise a ticket using this link (choose Office 365 Application): SAS ticket<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=82a1fc24db624050a01e9ef7db961937>

**Comment by MartinWhiteDAZN** [comment]
Hi Manuela,
I just realised I was responding to a different ticket. It's true that the October release removed the attachment and that has worked. My other comments related to Issue #1621.

Kind Regards

***@***.***
Martin White
Office 365 Development Manager
***@***.******@***.***>
Hanover House, Feltham, London, TW13 7BZ

For support with building SharePoint pages please raise a ticket here: Office 365 Help<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=787250db374e5b0020a0532e53990eaa>
For Office 365 process requests please raise a ticket using this link (choose Office 365 Application): SAS ticket<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=82a1fc24db624050a01e9ef7db961937>

From: Martin White
Sent: Friday, 17 December 2021 12:04
To: microsoft/coe-starter-kit ***@***.***>; microsoft/coe-starter-kit ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [microsoft/coe-starter-kit] [CoE Starter Kit - BUG] Developer Compliance Centre app - Not found segment 'annotations' (#1026)

Hi Manuela,
The October release removed the attachment field as that was preventing anyone from submitting the form.

When I tested it about a month ago I thought it the sharing was working.

I will try making a copy of DCC and strip out components to see if I can get it to share.

Kind Regards

***@***.***
Martin White
Office 365 Development Manager
***@***.******@***.***>
Hanover House, Feltham, London, TW13 7BZ

For support with building SharePoint pages please raise a ticket here: Office 365 Help<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=787250db374e5b0020a0532e53990eaa>
For Office 365 process requests please raise a ticket using this link (choose Office 365 Application): SAS ticket<https://performgroup.service-now.com/sp/?id=sc_cat_item&sys_id=82a1fc24db624050a01e9ef7db961937>

**Comment by mikefactorial** [comment]
@MartinWhiteDAZN This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
