### ISSUE TITLE
Some of the Sync Flows in the CoE Starter Kit have failed.

### ISSUE THREAD

**Issue by O365Support** [microsoft/coe-starter-kit#10631]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

SYNC SYNC HELPER - Cloud Flows

Error
Action 'See_if_already_in_Maker_Table' failed

Expression expected at position 17 in 'admin_makerid eq '.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.50.7

### What app or flow are you having the issue with?

SYNC HELPER - Cloud Flows

### What method are you using to get inventory and telemetry?

None

**Comment by mohamrizwa** [comment]
Hi @O365Support,
Thank you for reporting this issue.

I have identified the root cause and recommend you to update the value as shown below:
Before:

<img width="520" height="177" alt="Image" src="https://github.com/user-attachments/assets/1a57f68d-779d-44b1-a16a-3daef617da7b" />

After:

<img width="508" height="176" alt="Image" src="https://github.com/user-attachments/assets/a4e47595-9c86-4ec8-8e92-1d4f7e15daac" />

Once this change is applied, the flow should function correctly. These updates will be included in the next release.

**Comment by O365Support** [comment]
Thank you for the update is there any workaround until next release as if we edit the flow it will create unmanaged layer

**Comment by mohamrizwa** [comment]
Hi @O365Support,
For now, I kindly suggest updating the flow. Once this fix is released, you can upgrade to the latest version. Before upgrading, please remove the unmanaged layer from this flow.

**Comment by jackpoz** [comment]
FYI after updating the flow in the "Get Owner Details" scope, it fails further below in the "Upsert Flow Details" section:
<img width="537" height="436" alt="Image" src="https://github.com/user-attachments/assets/42e2714a-f4ce-447a-9612-fca5fbe30cb7" />

**Comment by mohamrizwa** [comment]
Hi @jackpoz,
Please debug the update action to determine where the incorrect data is coming from.

**Comment by jackpoz** [comment]
It's the same root cause that propagates further down after applying the change from null to "" you mentioned.

The action in my screenshot uses the output of IsOrphan action that is not set to true when owner is "". You will have to use a variable and set it to true in the branch of "If owner is null" when it's true.

I would strongly recommend to test this in your development environment or it will take months before all cases are properly taken into account, or restore the previous version that worked fine.

**Comment by O365Support** [comment]
> Hi [@O365Support](https://github.com/O365Support), For now, I kindly suggest updating the flow. Once this fix is released, you can upgrade to the latest version. Before upgrading, please remove the unmanaged layer from this flow.

Hi @mohamrizwa ,Post verification ,the reported bug is not fixed in latest version of COE i.e. -[CoE Starter Kit January 2026](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-January2026).It is still open ,kindly suggest.

**Comment by mohamrizwa** [comment]
Hi @jackpoz,
Please debug the flow, identify the action where it is failing, and share a screenshot for further investigation.

**Comment by jackpoz** [comment]
Are you a bot ? I already wrote here https://github.com/microsoft/coe-starter-kit/issues/10631#issuecomment-3728703574 .
I even wrote the solution to fix it.

Can Microsoft please re-hire the people that used to manage CoE Starter Kit ? The quality of this tool has fallen a lot in the past months.

**Comment by mohamrizwa** [comment]
Hi @jackpoz,
We apologize for the inconvenience. We will thoroughly investigate the issue in our development environment and work to resolve it as soon as possible.

**Comment by O365Support** [comment]
Hi @mohamrizwa ,

It seems above solution has been provided to fix this issue ,could you please update on this issue?

**Comment by trevorseward** [comment]
> Hi [@mohamrizwa](https://github.com/mohamrizwa) ,
> 
> It seems above solution has been provided to fix this issue ,could you please update on this issue?

Creating unmanaged layers is not a solution. The solution needs to be in a new release. PR #10721 has the fix for the original issue but fails to address the downstream Upsert and doesn't appear to be getting any attention as it is still in Draft

**Comment by mohamrizwa** [comment]
Hi @jackpoz,
Apologies for the delayed response. The issue has been resolved and will be included in the next release.

**Comment by O365Support** [comment]
Hi @mohamrizwa ,will it be included in Feb 26 CoE release or March 26?

**Comment by mohamrizwa** [comment]
Hi @O365Support,
Yes, it be included on Feb 26 release.

**Comment by mohamrizwa** [comment]
Hi @jackpoz,
This fix has been released, please verify and confirm the same.

**Comment by mohamrizwa** [comment]
We haven’t heard back in a while, so we’ll proceed to close this issue for now. If the issue persists or you need further assistance, feel free to a new issue. We’re happy to help anytime. Thanks again for your engagement!

**Comment by O365Support** [comment]
@mohamrizwa -This issue is not resolved ,we are getting below error for Maker ID's not available in Maker Data verse Table

<img width="1187" height="599" alt="Image" src="https://github.com/user-attachments/assets/2caaf345-ec78-4253-97c3-62a8ec35cf52" />

<img width="1187" height="605" alt="Image" src="https://github.com/user-attachments/assets/f7031bb4-c0ec-4505-8e2a-2702773cb8e7" />

<img width="1179" height="604" alt="Image" src="https://github.com/user-attachments/assets/78485559-7718-45bb-9d96-c0064143a81d" />
