### ISSUE TITLE
[CoE Starter Kit - BUG] Power Platform Request Center Error

### ISSUE THREAD

**Issue by medicineshow** [microsoft/coe-starter-kit#1101]
### Describe the issue

When a user opens the PP Request Center application, they receive the following error message across the top:
PowerAppsforMakers.GetConnectors failed: { "error": { "code": "MissingEnvironmentFilter", "message": "The environment filter must be set." } }

### Expected Behavior

The application to open without errors

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

Power Platform Request Center - Canvas App

**Comment by medicineshow** [comment]
Hi, do you have an update on this issue for me please?

**Comment by manuelap-msft** [comment]
This is fixed for the September release, which we're aiming to have out this week.

**Comment by mikefactorial** [comment]
@medicineshow This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by medicineshow** [comment]
I have updated the version in Teams and still get the same error.

**Comment by Jenefer-Monroe** [comment]
Re-opening for Denise

**Comment by manuelap-msft** [comment]
I don't repo this issue in Teams. You may have unmanaged solution layers that prevented you from receiving the latest upgrade, please see https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates on how to check for that.

**Comment by medicineshow** [comment]
The instructions for installing updates are not relevant to a Teams install. There is no setting for solution layers in Teams installed version. Please advise.

**Comment by manuelap-msft** [comment]
You will have to go to **flow.microsoft.com** > select your Teams environment > follow above steps to see solution layers

**Comment by medicineshow** [comment]
I am fairly sure that I do not have any unmanaged solution layers as this was installed, out of the box with no changes. Is there a way to check without going in to each flow?

**Comment by medicineshow** [comment]
I have also just noted that this has also happened in the production installation. And there are no unmanaged layers there.

**Comment by manuelap-msft** [comment]
As you're seeing the issue with the Power Platform Request Center app, you don't need to check the flows for unamanaged layers. Just the app that you're seeing issues with.

Please send screenshots of where you're experiencing the issue, and what the error looks like and when it happens (what you click etc). We don't repo this in either Teams or Production.

**Comment by medicineshow** [comment]
Apologies. There was an unmanaged layer. I have removed it but still get the error in both Production version and Teams. Do you think it might need a while to replicate around the microsoft cloud? Also not sure how it became an unmanaged layer as I made no changes.
![image](https://user-images.githubusercontent.com/17124284/133090189-7267445f-0fa9-4b20-a053-d8f611dc0056.png)

**Comment by manuelap-msft** [comment]
Hello,

an unmanaged layer will have prevented you from receiving the latest upgrades when you imported the latest version. You will have to perform the upgrade again to receive the latest version. Just removing the unmanaged layer won't mean you have the upgrade. 

If you select Edit on the app, that will create an unmanaged layer - so you may have opened the app in the editor.

Thank you
Manuela

**Comment by medicineshow** [comment]
OK, I have removed the unmanaged layer, re-imported the solution, but the same error is occurring when I open the app.

**Comment by manuelap-msft** [comment]
Can you share screenshots of 
- what it looks like when you click on Solutions (from either flow.microsoft.com for Teams or make.powerapps.com for Production)
- show solution layers for this app 
- click on Solution History (under Solutions) and see if the upgrade has finished (please share a screenshot)

**Comment by medicineshow** [comment]
This is production:
![image](https://user-images.githubusercontent.com/17124284/133094053-b5230146-aa9d-443b-96bf-46f750872574.png)

![image](https://user-images.githubusercontent.com/17124284/133094127-66f26e8c-781a-408e-a6b6-e3c8b2b95daf.png)

![image](https://user-images.githubusercontent.com/17124284/133094252-949caf2a-5eb8-4e71-9795-4914187af68b.png)

**Comment by manuelap-msft** [comment]
The latest version is 3.11 for Core, and 2.9 for Core for Teams. You can download them from here:
https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2021

**Comment by medicineshow** [comment]
Is there a way to see if you have any unmanaged layers without having to check each individual component?

**Comment by medicineshow** [comment]
I thought that at straight upgrade would have been problem free...

![image](https://user-images.githubusercontent.com/17124284/133099541-6410ae04-21ec-4d03-9b46-385c7a6b4a3a.png)

**Comment by manuelap-msft** [comment]
@Jenefer-Monroe can you please help provide Upgrade instructions! Thank you!

**Comment by manuelap-msft** [comment]
It looks like you may have unmanaged layers on the Set App Permission app as well. Try using Update instead of Upgrade when you perform the Import:
![image](https://user-images.githubusercontent.com/55705669/133100053-7af37af3-c956-4223-99cd-cc415882e9e5.png)

Further suggestions to try when the Upgrade fails are listed here for you to read up on #1130

**Comment by medicineshow** [comment]
I have upgraded in the Teams version and I still get the error that an environment filter is missing when I open the app

**Comment by medicineshow** [comment]
I am still getting the same error in both the Teams version and production. I have now got version 3.11 in production.
PowerAppsforMakers.GetConnectors failed: { "error": { "code": "MissingEnvironmentFilter", "message": "The environment filter must be set." } }

**Comment by medicineshow** [comment]
Hi, do you have any more suggestions for me please as this error is still showing. Worth noting that when a Power Platform admin opens the app, the error message does not appear

**Comment by manuelap-msft** [comment]
We are still looking into this; please note the CoE Starter Kit is not a supported set of tools and we can not provide an SLA for fixing bugs.

**Comment by medicineshow** [comment]
This appears to have worked :)
worth noting that when I edited the following was the current setting which had the line UpdateContext already but slightly different to the one you had supplied. So I removed it and added the one you sent.:
   /* Get all environments in tenant */
    ClearCollect(col_environments, PowerPlatformforAdmins.GetAdminEnvironment().value);
    UpdateContext({ varDefaultEnvironment : Coalesce( LookUp(col_environments, properties.isDefault), First(col_environments)) });

It now looks like this:
   /* Get all environments in tenant */
    //ClearCollect(col_environments, PowerPlatformforAdmins.GetAdminEnvironment().value);
    //UpdateContext({ varDefaultEnvironment : Coalesce( LookUp(col_environments, properties.isDefault), First(col_environments)) });
        ClearCollect(col_makerEnvironments, PowerAppsforMakers.GetEnvironments().value);
    UpdateContext({ varDefaultEnvironment : Coalesce( LookUp(col_makerEnvironments, properties.isDefault), First(col_makerEnvironments)) });

**Comment by manuelap-msft** [comment]
Awesome, thanks for checking this so quickly! 

I made the changes on our end as well, and we can hopefully include them in the October release if we don't stumble over anything during further testing. Please do loop back here if your users now experience any other issues with the app!

Thanks for your patience as we work through this bug!
Manuela
