### ISSUE TITLE
[CoE Starter Kit - BUG] Missing Spatial Services Connector

### ISSUE THREAD

**Issue by HamishSheild** [microsoft/coe-starter-kit#1113]
### Describe the issue

I'm not sure if this is an issue with the **Admin | Sync Template v3 (Connectors)** flow or with the Get Connectors action in the Power Apps for Makers connector but the **Spatial Services** connector does not get returned and is therefore not listed as a Connector in the Power Platform Admin View app.  

I just noticed a customer this week who is using the Spatial Services connector and has a Connection Reference record for it in the  Power Platform Admin View app but the lookup to Connector is blank.  This means that the Spatial Services connector does no show in the Power BI report for App Connections

### Expected Behavior

The Spatial Services connector should show as a Connector record in the Power Platform Admin View app. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.75

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Connectors)

### Steps To Reproduce

1. Run the Admin | Sync Template v3 (Connectors) flow
2. Search for "Spatial Services" in the list of Connectors in the Power Platform Admin View app. 
3. Spatial Services is missing

**Comment by Jenefer-Monroe** [comment]
Hi. Thanks for being so detailed in your notes. 

Indeed it appears that this connector is not returned from **_Get Connectors_**, even if you filter to environments in which the feature has been enabled. I also noticed that its not listed in documentation for [All Connectors](https://docs.microsoft.com/connectors/connector-reference/) so it could be that this part of the feature work wasn't done. 

I can add this to the limitations notes and have someone in the product team notified.

**Comment by manuelap-msft** [comment]
Hello,

we've done work to add this manually now so it should get picked up for canvas apps using those features. Will be included in the September release.

Thank you
Manuela

**Comment by mikefactorial** [comment]
@HamishSheild This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by BB553407** [comment]
This is still happening in our latest version .. x.x.45 I asked and it said it was going to get fixed in November 2024 release at the time. Now showing up as Microsoft Spatial Services in the list but the apps are not getting linked to it in Power BI.
