### ISSUE TITLE
[CoE Starter Kit - BUG] PowerBI template is not working

### ISSUE THREAD

**Issue by UrvishGT** [microsoft/coe-starter-kit#1547]
### Describe the issue

PowerBI templates are not working.
I tried both templates but they are getting issues to get data.
![image](https://user-images.githubusercontent.com/94638525/144074958-76fad181-9802-4539-9ab1-01676caa2ba4.png)

![image](https://user-images.githubusercontent.com/94638525/144075066-108ed583-b018-437c-a9b1-8ef85138df29.png)

Please find attached image for the errors.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

November 2021

### What app or flow are you having the issue with?

PowerBI templates

### Steps To Reproduce

1. Open the PowerBI template in Power BI desktop
2. Add Org Url
3. Getting an error after that while it connects to data.

**Comment by Jenefer-Monroe** [comment]
Can you please try the Dec version of the report available here: https://github.com/microsoft/coe-starter-kit/tree/coe-december/CenterofExcellenceResources/Release/Collateral/CoEStarterKit

We have fixed a similar sounding issue and want to see if yours is the same

**Comment by UrvishGT** [comment]
Thank you Jenefer. Its working like a charm now.

But Cloud Flows are still not showing any results in the report.
There are no errors while fetching the data.

Also I can see the Flows data in Power Platform Admin View app.

**Comment by Jenefer-Monroe** [comment]
Glad to hear thats resolved. Can you share pictures of what you are seeing, both in the PBI and in the Power Platform Admin View app? 
I have just tested the PBIT and it seems to be working so I'll need more details to understand.

**Comment by UrvishGT** [comment]
Its working fine now. Looks like there was some lag to get it connected to data.
Thanks Jenefer.
