### ISSUE TITLE
[CoE Starter Kit - BUG] Issue with Developer compliance App Mitigation Plan Field

### ISSUE THREAD

**Issue by sandeep-mamidala** [microsoft/coe-starter-kit#2615]
### Describe the issue

Hi Team,

We observed in  developer compliance app while maker submitting compliance details the Mitigation Plan should be made Yes.

But as per the instructions only for the critical solutions it should be Yes . But user when try submitting compliance details with 'No' in mitigation plan it is not submitting compliance details to admin.

Also even when mitigation Plan is 'YES' app is not checking whether the attachment has been provided or not before submitting the details for admin approval.

### Expected Behavior

We need user can select the 'NO' Option for non critical solution for Mitigation Plan field.

Also if user selected 'Yes' then app should check whether document is attached or not before submitting the compliance details to admin approval.

Thanks

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.13

### What app or flow are you having the issue with?

Developer Compliance App

**Comment by Jenefer-Monroe** [comment]
Hello, is 2.13 the version of Governance you are on? I believe this was addressed a few months ago and we now change the status to submitted regardless of what information they provided.

**Comment by sandeep-mamidala** [comment]
Hi Team,

We are in 2.13 version of Governance.But we checked still the issue is not fixed also there is no unmanaged layer for the app.We still see before submitting the compliance details still it is checking for "Yes" in mitigation plan field.Could you please verify and let us know.

Thanks

**Comment by Jenefer-Monroe** [comment]
Current version of Governance is 2.16. I dont remember when we made the fix but I did just confirm that we now mark as Submitted even if you dont add anything at all to the form. 

![Image](https://user-images.githubusercontent.com/89584709/166927474-261d9bc2-cfca-4820-9788-37795c2c626f.png)

You will need to upgrade to see this change. 
Thanks for using CoE

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
