### ISSUE TITLE
No Desktop Flow Data Present in Power Platform CoE Starter Kit RPA Tables

### ISSUE THREAD

**Issue by michaelgottwals** [microsoft/coe-starter-kit#3213]
Creating a new issue for this problem per Jenefer Monroe's instruction in Issue #3194. I am running version 3.21 of the CoE Components for Teams which is using the Power BI July 2022 Teams CoE Dashboard and no Desktop Flow data is showing in the reports. A look at the RPA tables via the Power BI Desktop software pointing to the Teams environment show no rows in the RPA tables. I also have the Oct 2021 version of the kit installed in another Teams site and the CoE dashboard from that time shows data for the desktop flows. The flows for that version are still running daily and when I check the the RPA tables in that Teams site it shows rows with values for the admin_rpacreatedon column that stop after June 30th, 2021. So it would appear something happened since then which caused the flow responsible for collecting desktop flow data to stop working.  Another thing to mention is this issue seems to be similar to issue #3025.

**Comment by Jenefer-Monroe** [comment]
Is this flow turned on, running and passing? **Admin | Sync Template v3 (Desktop flows)**

If so, please find one of the environments where you expect to see a desktop flow, 
![image](https://user-images.githubusercontent.com/89584709/180630144-70e505f3-e550-4c0c-bca3-b87a269262f5.png)

this will trigger the desktop flows flow and you can open the run and see if or why its not gathering the data.
![image](https://user-images.githubusercontent.com/89584709/180630130-8aa8b16c-e962-49f6-8b52-c668a835bac0.png)

**Comment by michaelgottwals** [comment]
Hello Jenefer, The Admin | Sync Template v3 (Desktop flows) flow is turned on and running in my Teams installed CoE starter kit.  The run history shows many runs daily within minutes of each other. When I look at the last few runs, they are successful, but the history shows it checking a Teams environment and it stops on the "Check if Desktop Flows can be retrieved for this environment" action taking the "If Yes" branch stating to "Terminate, inquiry not supported."  I'm not sure why the Desktop Flows flow would check Teams environments if desktop flows are not supported there. Regardless, we use an environment strategy of "Default" environment for all of our flows and apps except for the environments that are created in Teams sites. 

The default environment is where we have our Power Automate Desktop flows defined and when I check the Desktop Flows flow history with a filter of "Failed" I find the runs against the default environment fail with the following error:

![image](https://user-images.githubusercontent.com/79226165/181070985-1d7140bd-2c90-4866-8a60-21c0e6d5115e.png)

Based on existing data in the Desktop flows table from a previous CoE starter kit installation, the last data collected on desktop flows in our tenant was June 30th, 2021. Maybe something changed in the flow or in our tenant to start causing this, but the issue appears to be the buffer size of the data being written to the Desktop flows SQL table is too big.  Please let me know how I should proceed.

Thanks.

**Comment by Jenefer-Monroe** [comment]
For your question about why it doesnt inventory Desktop Flows for D4T environments, the product does not allow us to fetch the inventory from the dataverse tables in a D4T environment. This is documented [here in our limitations](https://docs.microsoft.com/power-platform/guidance/coe/limitations#sync-flow-limitations-for-developer-and-microsoft-team-environments). 

For your error, this is another limitation of the kit. Please see [our limitations](https://docs.microsoft.com/power-platform/guidance/coe/limitations#large-desktop-flows)
Unfortunately the desktop flow work in the CoE Starter Kit currently has several limitations that make it insufficient for organizations exclusively focused on that tech. This is due to the way that we gather the data and is not something we can fix without a product change (which is supposed to be coming live in a few months)

That said, there is a dedicated set of folks who work on "Automation CoE". My recommendation is that you focus in that direction instead. Here are some starter links to get you going:
- [Automation Center of Excellence Webinar](https://info.microsoft.com/ww-thankyou-businesscenterexcellencerpa.html?LCID=EN-US&ocid=eml_pg332504_gdc_comm_ba)
- [Microsoft Power Platform Automation CoE starter kit (preview)](https://docs.microsoft.com/power-platform/guidance/automation-coe/automation-coe-starter-kit)
- [RPA CLI](https://github.com/rpapostolis/rpa-cli)

**Comment by michaelgottwals** [comment]
If fetching inventory is not supported for D4T environments, the Teams version of the Desktop Flows flow(s) should not run for Teams environments. For companies with many Teams environments, this is unnecessary processing cycles and flow history entries burying meaningful flow run history.

Related to the errors I am receiving and the limitations you mention, I guess this limitation was introduced in the starter kit sometime after Aug 2021 because the kit was gathering and writing information back then. Really I was reporting the issue to your team so it could be addressed. I really just want the summary of how many desktop flows citizen developers have created in our tenant (environments). The dashboard has a place holder for the information but if the processes are not able to populate the data then either it should be fixed or that particular summary information removed from the dashboard. Is there any chance this will be fixed in future versions of the starter kit?

**Comment by Jenefer-Monroe** [comment]
This limitation is not in the kit but in the product itself. Your usage has increased past the limits the connector can support. 
The product team is making some changes to another connector so that we can use it instead, once that change is in production we will use that connector instead and the issue with size will be addressed.

**Comment by michaelgottwals** [comment]
OK, thanks for the explanation. It is good to know that eventually that information will be available again in the future. One side note question, was there any changes introduced in the August 2022 CoE Dashboard that addressed the IsSystem filter previously added which was preventing summary data from showing up on the Overview pages? I had mentioned this in issue #3194.

**Comment by Jenefer-Monroe** [comment]
yes i believe that was addressed.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team

**Comment by michaelgottwals** [comment]
Jenefer, FYI, I just installed the August 2022 Teams CoE Dashboard in my production environment and then published the dashboard to Power BI online and see the isSystem issue is still existing. I will open a separate issue on this.
