### ISSUE TITLE
Admin | Inactivity notifications v2 (Start Approval for Apps) fails due to typo

### ISSUE THREAD

**Issue by bwieland86** [microsoft/coe-starter-kit#4263]
The Governance Component workflow "Admin | Inactivity notifications v2 (Start Approval for Apps)" fails on the "Get Envt Name" action in the "Yes" branch of the "See if Approved" condition due to a typo:

InvalidTemplate. Unable to process template language expressions in action 'Get_Envt_Name' inputs at line '0' and column '0': 'The template language expression 'first(body('Parse_JSON_this_one_approved'))['admin_appenvironmentame']' cannot be evaluated because property 'admin_appenvironmentame' doesn't exist, available properties are '@odata.type, @odata.id, @odata.etag, @odata.editLink, admin_archiveapprovalid@odata.type, admin_archiveapprovalid, admin_appname, admin_appdisplayname, admin_appenvironmentname, admin_approvalresponsedate@OData.Community.Display.V1.FormattedValue, admin_approvalresponsedate@odata.type, admin_approvalresponsedate, admin_approvalresponse'. Please see https://aka.ms/logicexpressions for usage details.'.

Should be `first(body('Parse_JSON_this_one_approved'))['admin_appenvironmentname']` instead of `first(body('Parse_JSON_this_one_approved'))['admin_appenvironmentame']`

Result of not fixing this is the try / catch block processes and sends a backup reminder email template with no dynamic data.

![Power Platform CoE Inactivity notifications error](https://user-images.githubusercontent.com/13457692/203595039-83432896-b171-458c-9d40-cb7114a1e226.PNG)

![Power Platform CoE Inactivity notifications correction](https://user-images.githubusercontent.com/13457692/203595545-9b8ab9e1-385c-4417-a19d-d8a737ecdc01.png)

**Comment by manuelap-msft** [comment]
Hello,

this was fixed with the October release of the CoE kit, see #3683. What version of the Governance components are you on? And if you are on a recent version, can you make sure you don't have unmanaged layers on this flow which would have prevented you from receiving the update?

Thank you
Manuela

**Comment by bwieland86** [comment]
Hi, this was discovered while using the October release of the CoE kit. It is fixed in the Start Approval for Flows workflow, but not in the Start Approval for Apps workflow.

**Comment by manuelap-msft** [comment]
I see, thanks for the confirmation! Assigning to @Jenefer-Monroe for further triage

**Comment by Jenefer-Monroe** [comment]
Hello, at the time of fixing for flows I validated that it did not repro for the apps version of the flow, and I did just double check and I still dont see it there. 

Both correctly show: first(body('Parse_JSON_this_one_approved'))['admin_appenvironmentname']
![image](https://user-images.githubusercontent.com/89584709/203607230-9ba75509-eed1-48fc-adf1-b14f198d86c4.png)

Can you please check: **_Do you have an unmanaged layer on the flow?_**

**Comment by bwieland86** [comment]
Hi, it appears that we had the September release for CoE, it was simply installed in October, hence the confusion. Apologies for this and good to know that the issue was fixed in the October release. Please mark as duplicate.

**Comment by Jenefer-Monroe** [comment]
wonderful, thanks for confirming.
