### ISSUE TITLE
[BUG]: App Connectors validation vs Environment Usage

### ISSUE THREAD

**Issue by yearwoodm15** [microsoft/coe-starter-kit#536]
Hello,

Before applying DLP to our Power Platform environment we ran an analysis in the CoE to verify which connectors were being used by the environment under the "Connections" tab. Based on the connectors being used, we had put those connectors in the business categorization for users to continue to utilize and the other blockable connectors to the blocked classification.

That being said, we received user inquiries that they were unable to run some of the flows because our policy had blocked them from using a connector that was not authorized by the policy. For the sake of this example, we had verified that environment "ABC" was not using Microsoft Forms, so we had moved it to blocked. There is no data showing that environment "ABC" had ever used Microsoft Forms from the Connections tab of CoE. 

Could someone please assist as to why no data was shown? Is there somewhere else we need to be looking in order to confirm all connectors that environment "ABC" is using? We'd like to apply a DLP policy without breaking something again.

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Core]
 - Version [2.0.10]
 - App or Flow [Unsure]

**To Reproduce**
This error cannot be reproduced externally.

**Expected behavior**
We expected that through our CoE analysis that we caught all connectors that environment "ABC" was using and placed in our DLP policy without disrupting their daily business. Now we are unsure of which others we might have missed and would like guidance on how to verify before applying DLP again.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by yearwoodm15** [comment]
Hello Manuela, thank you for providing this information. Can you provide a screen shot of the "Apps (3 of 2000)" area? I'm not entirely sure where this is being referenced from within the CoE dashboard. Thanks again!

**Comment by manuelap-msft** [comment]
Hello,

we just released a new version of the CoE Starter Kit today, which should address the delegation issue you were seeing.

1. Please download the latest version via aka.ms/coestarterkitdownload
2. Please upgrade the Core Components solution following our Upgrade instructions https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup#installing-updates
3. Please run a Full Inventory once by updating the environment variable Full Inventory to "Yes" (https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components#update-environment-variables) and waiting for one day for the Admin | Sync Template flows to run and wait for them to finish. You can set Full Inventory back to "No" when all flows have finished running.

When you then open the DLP Editor, you should see all apps and DLP impacts.

Thank you for using the CoE,
Manuela

**Comment by yearwoodm15** [comment]
Hi Manuela,

I upgraded CoE last week and unfortunately this did not solve the issue. We continue to have users write in about DLP policy, but we cannot see the connector activity on our end through the dashboard. Is there a step I may be missing? We should be able to see all connector activity from apps and flows per Power Platform environment through the Connections area, is that correct?

**Comment by JeneferM-MSFT** [comment]
You will need to do a full inventory run to have this update for all the objects in your inventory. This is because the daily runs will only update for objects that have changed or which are new since the previous days run. 

Here is how to do a full inventory run [force full inventory run](https://docs.microsoft.com/power-platform/guidance/coe/limitations#incomplete-inventory)

**Comment by yearwoodm15** [comment]
Hey Jenefer,

Thank you for this info! Mine is greyed out, so it looks like I cannot proceed via the documentation steps. Any idea on how to resolve this? Please see below:

![image](https://user-images.githubusercontent.com/83036044/121206790-bed79f00-c846-11eb-8113-901efd4a1f2e.png)

**Comment by manuelap-msft** [comment]
You will have to navigate to the **Default solution** not the CoE solution to update the Environment Variable.

**Comment by yearwoodm15** [comment]
Ah okay, thank you! I ran the FullInventory via Default Solution and performed a data refresh on my CoE dashboard, let it run completely but am still unable to see the connectors under the Connections area of Power BI CoE dashboard that my users are mentioning. Is there something else I may be able to troubleshoot?

**Comment by yearwoodm15** [comment]
Hi Manuela/Jenefer, following up to see if there is any other troubleshooting I may be able to perform for this issue?

**Comment by JeneferM-MSFT** [comment]
IT sounds like the issue with the DLP editor is resolved and you are having an issue in another area. Is that correct?

**Comment by yearwoodm15** [comment]
Hi Jenefer, this issue is not DLP related. DLP was used as context for when we were running an analysis of the different connectors being utilized by our users so when we applied DLP those actively used connectors would be placed in the business category so it didn't impact their work. Seems like there were some connectors that were not showing up in CoE as being actively used, so those connectors were moved to blocked. We got some feedback from users that DLP stopped their work due because of this. 

That being said, we're trying to understand why some of the connectors that users mentioned that they were using prior to applying DLP did not show up as actively used in CoE. Some of these have been used for a long time, but CoE did not pick up on it. 

For example, Microsoft Forms connector was one that we moved to blocked in DLP because through CoE there was no analytical data. I've checked the Connections tab to verify but there is no data to provide any evidence that it was being used. However, when I spoke with the user they provided a live demo of the flow/app created that shows the Microsoft Forms connector. Shouldn't CoE pick up this data in the Connections tab where you can filter down by environment?

**Comment by JeneferM-MSFT** [comment]
I'm afraid we are speaking past each other here. When you say "CoE did not pick up on it" we are not sure what you mean, where you are not seeing it. There are multiple places in the toolkit that we surface and reference connections. The above referenced the DLP Editor, and we believe that is fixed. I'm not sure if you are still seeing the issue surfaced there or in the PBI report, or what. 

I am going to close out this issue now as the initial problem appears to have been the delegation issue which is resolved. And the issue back and forth makes readability difficult. 
If you are still seeing a problem please post a new issue and share screenshots of exactly where in the CoE Toolkit you expected to see a connection but did not. 

Thank you for using CoE.
