### ISSUE TITLE
Update the Power BI Maker Maps for the App, Flow, and Chat Bots Overview Reports

### ISSUE THREAD

**Issue by VA-smcvey** [microsoft/coe-starter-kit#577]
**Is your feature request related to a problem? Please describe.**
When viewing the Overview pages in the Power BI report, the maps for the top makers shows incorrect locations.  For example, a US-based organization is showing maker locations in Europe and Australia.  It is understood why the location is incorrect: the report is based on the admin_city field which is ambiguous for Bing Maps to geolocate.  For example, St. Petersburg could be in Florida or in Russia.

**Describe the solution you'd like**
The map should reflect the location of the maker based on the data that is available in the tenant AAD. e.g. the city, state, zip, country.

**Describe alternatives you've considered**
Updating the Starter kit flow to pull the maker User's state and zip from AAD.  Updating the Power BI query to incorporate state and zip.  Updating the report map to geocode the location based on this data.

**Comment by manuelap-msft** [comment]
Hello,

what version of the Power BI Dashboard are you using? This was previously reported (https://github.com/microsoft/powerapps-tools/issues/628) and fixed in the January or February release of the CoE Starter Kit.

If you look at the map visual, the location should be a new column called "Country, City" that is calculated in Power BI.
![image](https://user-images.githubusercontent.com/55705669/120986518-9aab8d80-c774-11eb-8a15-625e21a58cb5.png)

Thank you,
Manuela

**Comment by VA-smcvey** [comment]
Manuela,

Thank you for the clarification.  I was looking at a published report from the December version, but have now updated the service with the February version which does have the Country, City field.  Apologies for missing the version aspect.  At least now I can point to the missing "Country" field values in the organization's  AD/AAD for some Users as the cause for the 'Australian' pushpins on the map.  :)

**Comment by jamescgolding** [comment]
![image](https://user-images.githubusercontent.com/25093000/133130992-3ffe2e43-63fb-415a-8c8d-08cec137893e.png)
After downloading the COE Starter Kit on August 1, 2021 and Installing it into a teams environment, the same issue as mention above is present in our COE starter Kit.
All makers in our environment should be located within the United States. The COE Starter kit does not seem to pull in the state nor the country [United States]. This causes Bing to geolocate places incorrectly.

**Comment by manuelap-msft** [comment]
Can you please raise a new issue as this one is closed and we're no longer investigating it?

We also released a new version of the CoE Starter Kit in September, please update to the latest version which is the only one we can support: https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-September2021

**Comment by jamescgolding** [comment]
I updated to the September2021COEStarterKit as suggested on September 14. Nothing changed. The Overview pages in the Power BI report still shows incorrect locations. Even though the [country],city pairs are there in each map pin, most of the map pins do not contain [country]. In our case all makers are located within the United States.

**Comment by manuelap-msft** [comment]
We get that information from Active Directory, via the Office 365 Users table. Can you confirm the Country is present there?
