### ISSUE TITLE
Upgrade of COE Starter KIT Core Component to latest version 4.9 fails

### ISSUE THREAD

**Issue by VimmiRawat** [microsoft/coe-starter-kit#5888]
### Does this question already exist in our backlog?

- [X] I have checked and confirm this is a new question.

### What is your question?

We tried upgrading COE Starter Kit Core Component to version 4.9 from 4.3.  It failed with below error 

Solution dependencies exist, cannot uninstall. DependencyCount : 9 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCoEConnection, Id: fb97c6b8-6f62-41a0-9773-817026420eb1, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_CDSCurrentEnvironmentCoEConnection, Id: ac046569-9130-471d-9c61-975e671c10dd, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Compliance detail request, Id: 11f2ff3d-0987-e911-a856-000d3a372932, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365groups_d6648, Id: b2fa209f-683d-40a4-8ea0-b7edc16e4b65, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP HELPER - Power Apps User Shared With, Id: 1f3f24ff-c717-ec11-b6e6-000d3a1c26f9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365groups_d6648, Id: b2fa209f-683d-40a4-8ea0-b7edc16e4b65, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: Admin | Add Maker to Group, Id: 0ad4fe7a-6a5f-ec11-8f8f-0022481d6e1e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_bd471, Id: 2e30268c-2f6e-40df-8046-edb617caa702, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: CLEANUP HELPER - Power Apps User Shared With, Id: 1f3f24ff-c717-ec11-b6e6-000d3a1c26f9, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_bd471, Id: 2e30268c-2f6e-40df-8046-edb617caa702, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: HELPER - CanvasAppOperations, Id: 41263d72-4dea-eb11-bacb-000d3a5786fb, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_bd471, Id: 2e30268c-2f6e-40df-8046-edb617caa702, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: HELPER - CloudFlowOperations, Id: 6093b58a-4fea-eb11-bacb-000d3a578f6c, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_bd471, Id: 2e30268c-2f6e-40df-8046-edb617caa702, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: DLP Editor>Parse impacted resources into CSV, Id: 3acddf40-8d5e-ec11-8f8f-0022481d6e1e, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000 RequiredComponentObject details: Type: connectionreference, ObjectName: admin_sharedoffice365users_bd471, Id: 2e30268c-2f6e-40df-8046-edb617caa702, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000, DependentComponentObject details: Type: Workflow, ObjectName: HELPER - Maker Check, Id: 9301f01a-cb40-ec11-8c62-00224829b4c1, ParentObjectName: , ParentId: 00000000-0000-0000-0000-000000000000

After it failed , it shows two version of Core Component ( 4.3 and 4.9 )

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

June 2023

### What app or flow are you having the issue with?

All

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Can you please let me know what region your envt is in as well as its type? This can be found in the product admin pages: https://admin.powerplatform.microsoft.com/
![image](https://github.com/microsoft/coe-starter-kit/assets/89584709/4c23e8c8-2f8b-4d8b-af43-79a9f289be69)

And also share a screenshot with what solutions you have installed in this environment? Be sure to expand the indicated columns so that we can see full names
![image](https://user-images.githubusercontent.com/89584709/221184839-4ed24d69-24ac-426e-a909-889e3b230166.png)

**Comment by VimmiRawat** [comment]
Our Environment is Production Type and it's region is United States.  

For some reason, I am not able to drag to show the complete column name , it looks like below . We are trying to upgrade Core Component . It shows two with name as 

CenterofExcellenceCoreComponents_Upgrade  4.9
CenterofExcellenceCoreComponents                  4.3

<img width="776" alt="Screenshot 2023-06-20 002234" src="https://github.com/microsoft/coe-starter-kit/assets/62638075/ae84a37c-6993-4b73-897a-78d3c716fc47">

**Comment by Jenefer-Monroe** [comment]
Hello, it looks like you are still struggling with the same issue as https://github.com/microsoft/coe-starter-kit/issues/3605
I recommend you create a new environment and start from scratch. Your state is not one that we can assist with.

**Comment by VimmiRawat** [comment]
But that was fixed . That's why we were able to upgrade to 4.3 version in the month of March and this time again upgrade to 4.9 failed

**Comment by Jenefer-Monroe** [comment]
Your upgrade to 4.3 was not clean. This is evident form the fact that it still shows as being 2 years old.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
