### ISSUE TITLE
[CoE Starter Kit - BUG] I PP Administation planning component - PowerBI report issue

### ISSUE THREAD

**Issue by amolyadav90** [microsoft/coe-starter-kit#5975]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Getting error while creating PowerBI report for power platform administation planning component.
Power BI . 
PP admin planning component successfully installed on power platform,without any error . Excel imported successfullu for admin tasks, Tasks appearing in Admin task power app, no any unmanaged layer created.

**Error : pcat_admintasks
Microsoft SQL: A network-related or instance-specific error occurred while establishing a connection to SQL Server.**

![image](https://github.com/microsoft/coe-starter-kit/assets/137497313/4f862c78-1461-4c3f-8999-fe58fb664277)

### Expected Behavior

PowerBI report should display insight of PP admin planning comp

### What solution are you experiencing the issue with?

Admin Task Planner

### What solution version are you using?

admintaskanalysis_core_1_2_managed

### What app or flow are you having the issue with?

PowerBI report

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

-Install PP Admin component
-Import  Power Platform Administration Planning template into PowerBI desktop application

**Comment by manuelap-msft** [comment]
Please scroll through the Troubleshooting section here as this error is addressed there:
https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-powerbi#troubleshooting#5955 

![image](https://github.com/microsoft/coe-starter-kit/assets/55705669/b5a2b6d2-631a-4cd3-a74f-d9eb60d90c24)

**Comment by amolyadav90** [comment]
@manuelap-msft @Jenefer-Monroe  I followed steps which are in troubleshooting section which doc refered by you, but issue still persist,getting same error message.

**Comment by Jenefer-Monroe** [comment]
I'm afraid this error is in the product and not in our PBIT file, so some configuration error has occurred, its not something we can debug further than the above remotely. Perhaps the PBI community would have ideas. Please do let us know what you learn and we can augment our product troubleshooting.

**Comment by amolyadav90** [comment]
@Jenefer-Monroe  seems same issue already register in git hub, Can you please look into below link.
https://community.fabric.microsoft.com/t5/Desktop/COE-Toolkit-Admin-Task-Power-BI-report-TDS-error/td-p/2773572

**Comment by Jenefer-Monroe** [comment]
Does the recommendation there resolve the issue for you?

**Comment by amolyadav90** [comment]
We are connecting to network team for that,but not sure network team will approve it . Is there any other workaround on it?

**Comment by Jenefer-Monroe** [comment]
Not that I am aware of.

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for starter kit team
