### ISSUE TITLE
[CoE Starter Kit - BUG] Repeatedly prompted to republish Apps shared with a wide audience

### ISSUE THREAD

**Issue by Service-WebDevPowerP** [microsoft/coe-starter-kit#7516]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Owners of apps that are shared with a wide audience are prompted every week to republish their apps, but when you go into the Developer Compliance app and select the app the publish button is not visible

![image](https://github.com/microsoft/coe-starter-kit/assets/105202791/c6f6d3a8-c593-4e14-b435-f485f4d2ce01)

![image](https://github.com/microsoft/coe-starter-kit/assets/105202791/5c9c0e78-4aea-4d43-b775-5b9ea50aee88)

### Expected Behavior

Publish button would be visible and then once republished they should not be promoted again until scheduled (currently being prompted every week)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.13

### What app or flow are you having the issue with?

Developer Compliance App & Admin | Compliance detail request v3

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Create an app that is shared with a wide audience
when prompted try to republish the app

AB#2110

**Comment by Jenefer-Monroe** [comment]
There was a bug in the way we fetch last published date which was resolved in the Sept release. 
https://github.com/microsoft/coe-starter-kit/issues/5680

It looks like you are on Oct release or later, so you will need to flag these apps to be inventoried (with the InventoryMe flag) and then you will get the correct last published date

**Comment by Jenefer-Monroe** [comment]
closing out as no further action for the starter kit team

**Comment by Service-WebDevPowerP** [comment]
I am still receiving this emails on a weekly basis, i have individually set the Inventory Me flag to Yes for each of these apps and even tried a full sync but the emails still come every week
