### ISSUE TITLE
[CoE Starter Kit - Documentation Request] Add RPA Size issue to Limitations list

### ISSUE THREAD

**Issue by JeneferM-MSFT** [microsoft/coe-starter-kit#789]
### Describe the issue

Currently large Desktop Flows (RPAs) will fail to be collected in inventory due to a product limitation. 
This was covered in #419 .
We should add this to the limitations documentation so people can see and be aware while we await the product change. 

### Expected Behavior

Limitations page holds this information. 

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

2.2

### What app or flow are you having the issue with?

Admin | Sync Template v3 (Desktop flows)

### Steps To Reproduce

1. Have large Desktop Flow
2. Run inventory

### Anything else?

Today we use the Legacy connector to Dataverse as it allows us to select different environments to query, and the data for these is stored in each env in the tenant. And the new Dataverse connector does not yet let us pick which envt to query, always current.
Unfortunately Legacy connector does not let us select which fields to bring back, and while we do not use this field, and could chose to not use it, we cannot chose to not bring it back with this connector.
Connector team is making selection of envt available to the new Dataverse Connector and we will replat the suite to it for this sync flow and others that rely on it.
Until then this is a limitation in the toolkit.

**Comment by JeneferM-MSFT** [comment]
fixed for august documentation.

**Comment by mikefactorial** [comment]
@JeneferM-MSFT This has been fixed in the latest release. Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by Yashina-MSFT** [comment]
Has this issue been resolved or only listed as limitations of CoE? We are still encountering the same error covered in #419.
