### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Request | Sync Policy to Dataverse (Child) Failing

### ISSUE THREAD

**Issue by KRhoadesHyp** [microsoft/coe-starter-kit#7955]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

We last updated our core components on 2/9 to version 4.23.  Since 2/28 we have been seeing a fail in the **DLP Request | Sync Policy to Dataverse (Child)** flow.  
![image](https://github.com/microsoft/coe-starter-kit/assets/135135789/b10220cc-b8ff-420c-9243-947f6c59f419)
There is only one fail in the loop (row 32/1114), yet the entire flow indicates a fail
![image](https://github.com/microsoft/coe-starter-kit/assets/135135789/33410cd4-8fbd-4238-9233-cedb82f4a863)

If this flow fail indication is the intended behavior, how can I troubleshoot without spending an entire day decoding the flow?  This is the relevant data, with the error text following.
![image](https://github.com/microsoft/coe-starter-kit/assets/135135789/f1b7bf40-3015-44eb-bd07-3fcdacad3cfc)

`{
    "statusCode": 400,
    "headers": {
        "Cache-Control": "no-cache",
        "x-ms-service-request-id": "57940969-cce1-4f6e-bb4a-22722115315c,96e2d8eb-94aa-4d3a-b4d1-d42da7ee296f",
        "Set-Cookie": "ARRAffinity=39bb660144ceea45168e0a9d28fde75a566f48333c960b502c1a931df0a1b8d528ab763a81e504f280099b93126b2ba41a6b0a7ba7c8ae43fd9b7438b2f5d43308DC4EC1F3E7205D1143113017; path=/; secure; HttpOnly,ReqClientId=c3060816-7eee-40b3-9e89-434115c50f95; expires=Wed, 28-Mar-2074 00:26:50 GMT; path=/; secure; HttpOnly,ARRAffinity=39bb660144ceea45168e0a9d28fde75a566f48333c960b502c1a931df0a1b8d528ab763a81e504f280099b93126b2ba41a6b0a7ba7c8ae43fd9b7438b2f5d43308DC4EC1F3E7205D1143113017; path=/; secure; HttpOnly",
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
        "REQ_ID": "96e2d8eb-94aa-4d3a-b4d1-d42da7ee296f",
        "CRM.ServiceId": "framework",
        "AuthActivityId": "0f65c53c-01dc-4d54-b341-9c37ab21690d",
        "x-ms-dop-hint": "96",
        "x-ms-ratelimit-time-remaining-xrm-requests": "1,197.79",
        "x-ms-ratelimit-burst-remaining-xrm-requests": "7949",
        "mise-correlation-id": "f22f3207-e687-4424-8b1b-d53e4a24cb01",
        "OData-Version": "4.0",
        "X-Source": "61451201195454261192166919514898246252362402231124198126316013751117612392280,22820121912812820387143236342031872044326226812411375416824217518221201231307012046",
        "Public": "OPTIONS,GET,HEAD,POST",
        "Date": "Thu, 28 Mar 2024 00:26:50 GMT",
        "Allow": "OPTIONS,GET,HEAD,POST",
        "Content-Type": "application/json; odata.metadata=minimal; odata.streaming=true",
        "Expires": "-1",
        "Content-Length": "75"
    },
    "body": {
        "error": {
            "code": "0x80060888",
            "message": "The value of $id '' is invalid."
        }
    }
}`

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

DLP Request | Sync Policy to Dataverse (Child)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

DLP Request | Sync Policy to Dataverse (Child) runs daily & fails.

AB#2689

**Comment by Jenefer-Monroe** [comment]
To area owner for investigation.

**Comment by KRhoadesHyp** [comment]
Our flow is now being disabled due to this error, any help would be appreciated.

**Comment by Secretss7** [comment]
Here's how to manually fix your flow:
![image](https://github.com/microsoft/coe-starter-kit/assets/37102423/7ef596b6-463e-4ac1-8659-5ba9c776c787)

**Comment by kumashiro17** [comment]
Hello @Jenefer-Monroe , 

we have the same problem in our CoE production environment. Do you think that this bug will be fix in the november realease of the CoE ? 

thanks

Pat

**Comment by Jenefer-Monroe** [comment]
Can you validate if the fix suggested above resolves for you? If so I can try to pull it into an upcoming release.

**Comment by kumashiro17** [comment]
hello @Jenefer-Monroe, 

I applied the changes and restarted the flow manually and it ended successfuly 

Thanks

Pat

**Comment by Jenefer-Monroe** [comment]
Thank you for confirming. I'll take this one on my plate then to resolve for an upcoming release. 
Thank you @Secretss7 for sharing your work!!!

**Comment by Jenefer-Monroe** [comment]
made these changes for Nov release.

**Comment by Jenefer-Monroe** [comment]
Fix is available in Nov release. Please see [latest release](https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-November2024) to see all changes or just download directly via https://aka.ms/coestarterkitdownload

**Comment by Daren2023** [comment]
> made these changes for Nov release.

Good Afternoon Jenefer,

I have updated to the November update and we are experiencing this same error after our TA did changes to the DLP policies.

-Daren

**Comment by Jonson1501** [comment]
@Jenefer-Monroe - Still experience the same issue even we update to the Nov 2024 release patch. 

![Image](https://github.com/user-attachments/assets/a267111b-36bf-45af-9551-a17fe651807b)
