### ISSUE TITLE
[Power Platform communication site template] PnP Powershell module requires PS version 7.2 or higher

### ISSUE THREAD

**Issue by pnoot7** [microsoft/coe-starter-kit#8139]
### Describe your bug, question or feature ask.

Documentation and install process for the hub needs review/revision. The PnP PowerShell module requires PowerShell 7.2 or higher, it will not run on 5.1 anymore. However, the documentation states the Microsoft.PowerApps.Administration.PowerShell module requires 5.1. The install "mostly" completes using PowerShell 7.3, but there are clearly issues with it (doesnt have navigation or header for example). Install process needs to be refreshed, or possibly completely reworked. Use the deploy script on PS 7.3 then the setup script on 5.1? Not sure if that is viable, did not test it. I installed it all in a demo tenant.

**Comment by pnoot7** [comment]
Should also note the first time doing a connection with PnP PowerShell, it requires a great deal of permissions for an app registration. I see there is a small note under troubleshooting, but this should be more prominent in the documentation.

**Comment by ghcdb** [comment]
+1 on this issue

**Comment by mohamrizwa** [comment]
We noticed that this issue has been pending for quite some time. In the absence of further communication, we are proceeding to close this ticket, assuming that your concerns have been addressed or resolved. 
If you continue to experience any difficulties related to this matter, please feel free to open a new support ticket. This will help us ensure prompt and effective assistance, rather than reopening the new Issue. 
Thank you for your understanding and cooperation.

**Comment by pnoot7** [comment]
It's not fixed... but it appears the CoE team has abandoned it. You cannot install it with the current posted instructions, along with several features do not work. I have not been using it, as the CoE team never replied/helped with this issue.

I have NO idea how you think this is resolved.
