### ISSUE TITLE
[CoE Starter Kit - BUG] Compliance process - prerequisite flow check wont continue

### ISSUE THREAD

**Issue by SWIBR** [microsoft/coe-starter-kit#8608]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

I set up CoE with core and Governance components and after upgrading both components later i'm unable to go to the "setup" wizard for everything that is the Governance component.  It keeps telling me i'm issing prerequisites wich is running the 2 flows after comfirming both flows have successfully ran and pressing the refresh button i'm still unable to move forward. 

![2024-07-08 15_26_41-Manage your flows _ Power Automate and 3 more pages -  InPrivate  - Microsoft​ E](https://github.com/microsoft/coe-starter-kit/assets/175023927/d57ed435-dcb7-4e97-9723-a17a13d2b52c)
![2024-07-08 15_26_46-Manage your flows _ Power Automate and 3 more pages -  InPrivate  - Microsoft​ E](https://github.com/microsoft/coe-starter-kit/assets/175023927/46c20623-37fd-4161-a89c-743278707166)
![2024-07-08 15_26_10-Compliance Setup wizard page - Power Apps and 3 more pages -  InPrivate  - Micro](https://github.com/microsoft/coe-starter-kit/assets/175023927/1398a8d5-d06f-477b-a4e1-63de1be57301)

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.24(audit) & 4.32(core)

### What app or flow are you having the issue with?

Setup Wizard

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by Jenefer-Monroe** [comment]
Hello, 

All dialogs and panels were broken in the kit due to a product change that broke the creator kit components that we use. 
This has been resolved with the latest version of the creator kit: https://aka.ms/creatorkitdownload
- Creator Kit Core 1.0.20240529.1

Then this new version of creator kit has been adopted and used to fix in the June 2024 release of the kit: https://aka.ms/coestarterkitdownload

You will need to install the new creator kit and then at least June release of the kit which is the versions below to see this fix across the kit.
- Core 4.32.2
- Gov 3.24
- Nurture 3.18

**Comment by SWIBR** [comment]
> Hello,
> 
> All dialogs and panels were broken in the kit due to a product change that broke the creator kit components that we use. This has been resolved with the latest version of the creator kit: https://aka.ms/creatorkitdownload
> 
> * Creator Kit Core 1.0.20240529.1
> 
> Then this new version of creator kit has been adopted and used to fix in the June 2024 release of the kit: https://aka.ms/coestarterkitdownload
> 
> You will need to install the new creator kit and then at least June release of the kit which is the versions below to see this fix across the kit.
> 
> * Core 4.32.2
> * Gov 3.24
> * Nurture 3.18

After upgradeing the Creator Kit Core and checking the versions of Core & Gov in my environment the issue persists.

![2024-07-09 08_40_14-Power Apps _ Solutions and 3 more pages -  InPrivate  - Microsoft​ Edge Beta](https://github.com/microsoft/coe-starter-kit/assets/175023927/8d24c9fd-888b-485c-8011-dfa9160aa355)

**Comment by SWIBR** [comment]
Fixed it by delting the Governance Solution and importing it again.
