### ISSUE TITLE
[CoE Starter Kit - BUG] Power BI Template App Deep Dive incorrect "Users Shared with" count

### ISSUE THREAD

**Issue by julian0723** [microsoft/coe-starter-kit#8667]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

Notice an inaccurate value of the "Users Share with" in the App Deep Dive Tab. It is showing a value of 32000 for almost most of the app.

This was seen after the updating to July release and using the template Production_CoEDashboard_July2024.

![image](https://github.com/user-attachments/assets/101bd251-fd7b-4728-95e2-1784bf6e77c8)

### Expected Behavior

We expect to see the correct "User Shared With" count. it is hard to believe that almost most of the apps has large increment after a month.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.33

### What app or flow are you having the issue with?

Production_CoEDashboard_July2024

### What method are you using to get inventory and telemetry?

None

### Steps To Reproduce

1. Use the July 2024 Github Release
2. Generate a report using the Production_CoEDashboard_July2024 template.
3. Inaaccurate values "Users Shared with"

AB#3823

**Comment by Jenefer-Monroe** [comment]
I don't repro. We did have bug that was fixed in July that impacted the way we count group memberships. https://github.com/microsoft/coe-starter-kit/issues/8475

It requires those flows rerun before you would see it fixed. 
Please validate these flows have no unmanaged layers:
- CLEANUP HELPER - Power Apps User Shared With
- CLEANUP - Admin | Sync Template v3 (App Shared With)

And that these flows have run since your upgrade was complete:
- CLEANUP - Admin | Sync Template v3 (Flow Shared With)
- CLEANUP - Admin | Sync Template v3 (App Shared With)

**Comment by julian0723** [comment]
Issue remains the same, there is no unmanaged layers  for the following flows:

**CLEANUP HELPER - Power Apps User Shared With**
![image](https://github.com/user-attachments/assets/be563c1c-567d-4111-86bd-b7ee3a175db1)

**CLEANUP - Admin | Sync Template v3 (App Shared With)**
![image](https://github.com/user-attachments/assets/a5e05f2b-f32b-4634-97d5-274667c8ee1f)

**CLEANUP - Admin | Sync Template v3 (Orphaned Users)**
![image](https://github.com/user-attachments/assets/f951e1cd-3b0c-4085-ba98-67eba56b0d43)


**And retriggered the reruns for the flow:**
CLEANUP - Admin | Sync Template v3 (App Shared With)
![image](https://github.com/user-attachments/assets/c1172dbe-9ccd-45e1-9201-5765adb961cb)


**Refreshed Data Set**
![image](https://github.com/user-attachments/assets/9aba9c82-f6c6-44e0-9a47-da6421818c72)

Are we missing something?

**Comment by Jenefer-Monroe** [comment]
Please take one of the apps you believe to be incorrectly tallied (one of the rows in the image you shared) and find it in the Power Platform Admin View app, click the name to open and go to the shared with tab. Look through the users / groups. Especially the groups. Do any appear to be off? You can also click the "App Details" to compare with what the product shows for shared with

![image](https://github.com/user-attachments/assets/864f2c42-37af-4514-997e-23b41ea198a9)
![image](https://github.com/user-attachments/assets/f55991e4-c232-40bb-8e52-cb3cc71e78d7)

**Comment by julian0723** [comment]
It looks like it is indeed the actual report and, we found that the apps is shared to "Everyone". 
![image](https://github.com/user-attachments/assets/8d9e025e-f3f6-44d7-8b64-41256dfc58e1)

One thing that is not clear to us. why was it different on the previous report? 

In the previous report the count seems to be low. is "Everyone" and group membership (e.g DLs) not counted before?
![image](https://github.com/user-attachments/assets/71831526-81c5-4fc6-82d8-ca5eaba9afbe)

**Comment by Jenefer-Monroe** [comment]
Correct we did not tally the groups in the past, this was done in July release (I believe, or June).

**Comment by julian0723** [comment]
Got it, we can close the task.
