### ISSUE TITLE
[CoE Starter Kit - BUG] Dashboard failed to refresh - 'admin_totalshared' table wasn't found

### ISSUE THREAD

**Issue by velemilosavljevic** [microsoft/coe-starter-kit#8840]
### Does this bug already exist in our backlog?

- [X] I have checked and confirm this is a new bug.

### Describe the issue

After updating CoE Starter Kit Core and Audit components to the lates versions (4.37 and 3.25), dashboard fails to refresh. 

I receive the following error message:
Data source errorExpression.Error: The column 'admin_totalshared' of the table wasn't found.. admin_totalshared. . The exception was raised by the IDbCommand interface. Table: Power Apps.

### Expected Behavior

During previous updates of the CoE Starter Kit, this hasn't happened.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.37

### What app or flow are you having the issue with?

Sync template

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Error occured after update to the latest version.

**Comment by Jenefer-Monroe** [comment]
Hello this field was removed but we missed a couple spots in the PBI. 
This was resolved in the August release. I think the PBIT file there should work for you. 
Please see https://github.com/microsoft/coe-starter-kit/releases/tag/CoEStarterKit-August2024

**Comment by velemilosavljevic** [comment]
Hi Jenefer, 
thanks for your reply. 
I did install the August release, but the issue is still there. What do I need to do to resolve it so that my dashboard works again?

![CoE](https://github.com/user-attachments/assets/99ff2ec2-e50f-42ad-be9c-55405bcdf7c4)

**Comment by Jenefer-Monroe** [comment]
Did you use the August PBIT file from the release?

**Comment by velemilosavljevic** [comment]
Hi Jenefer,
apologies, forgot to publish the new PowerBI dashboard to my workspace. It works now, thanks!
