### ISSUE TITLE
[CoE Starter Kit - BUG] ISSUE TITLE We cannot convert the value null to type Text

### ISSUE THREAD

**Issue by PowerN00b** [microsoft/coe-starter-kit#9457]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Looks like this issue has happened a few times in the past [2845](https://github.com/microsoft/coe-starter-kit/issues/2845) / [7298](https://github.com/microsoft/coe-starter-kit/issues/7298) / [8311](https://github.com/microsoft/coe-starter-kit/issues/8311). 

I am setting up the CoE in my organisation for the first time and have the November 2024 release Core 4.45 / Production_CoEDashboard_November2024.pbit. I followed all of the setup instructions and videos and all flows etc are running. When I came to the PowerBi part (bear in mind this is my first use of PowerBi) I received errors. I had to download and install the latest version of PowerBi desktop so it was a clean install. 

First of all I didn't get the popup to enter the URL for my CoE environment but I managed to figure out how to locate and update that by editing the queries under model view. That has just left me with the error: 'We cannot convert the value null to type Text' on the AI Credits Usage part of this report.

![Image](https://github.com/user-attachments/assets/8418384d-8417-40a1-af0e-d88260343cce)

I have no clue about PowerBi query syntax so not sure if the below which is as it came is correct etc. 

![Image](https://github.com/user-attachments/assets/86f41ac2-8b89-44bc-85ac-93f29e95c75d)
When you click on the 'Edit Settings' button the following window appears

![Image](https://github.com/user-attachments/assets/fa81ba36-c3a0-457c-94b0-f42ea1947799)

I'm assuming as a new user of this I have missed something or am unaware of an action to take, any assistance will be appreciated as i'm keen to get this configured and working. This is all running from my global administrator account that I used to set this all up. 

As the issue relates to the AI Credits Usage i've checked the run history of the 'Admin | Sync Template v4 (AI Usage)'
![Image](https://github.com/user-attachments/assets/a72865ed-b7dd-4559-a726-4938ba259c56)

### Expected Behavior

I'm expecting the report to load data as standard with the CoE starter kit

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.45

### What app or flow are you having the issue with?

Production_CoEDashboard_November2024.pbit

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

1. Setup CoE starter kit with the 4.45 / November 2024 release as normal
2. Attempt to run the CoEDashboard.pbit

**Comment by Grant-Archibald-MS** [comment]
This issue is related to Reports have problem #9438

**Comment by PowerN00b** [comment]
Hi @Grant-Archibald-MS thanks for getting back to me, hope you guys had a great break. I'll look out for the updates on this.

**Comment by russrimm** [comment]
@Grant-Archibald-MS was this resolved in the Feb or Mar update? Should it be closed out?
Thanks

**Comment by soumya67** [comment]
@russrimm , 
To my surprise, I see that the pbit included in the March 2025 release is still for November 2024 and to me it is not fixed!

**Comment by pbattini** [comment]
@russrimm We've picked up this issue and will aim to include it as part of the April release.

**Comment by RajeevPentyala** [comment]
@russrimm and @soumya67 Apologies for the delayed response.
@PowerN00b Have you tried using the Production_CoEDashboard_April2025 file?. Please test it and let us know if you are still experiencing the issue.

![Image](https://github.com/user-attachments/assets/8dc16b02-1471-48cd-9f31-c451562cb0c5)

**Comment by RajeevPentyala** [comment]
@PowerN00b Closing the ticket as there has been no update. Please reach out if you need any further assistance.
