### ISSUE TITLE
[CoE Starter Kit - BUG] DLP Editor issue - delegation

### ISSUE THREAD

**Issue by ALMAcclerator** [microsoft/coe-starter-kit#958]
### Describe the issue

We have an issue with the DLP Editor V2 application included in the core components of the CoE Starter Kit. We are using this tool for Impact analysis to identify the impact of applying a test DLP Policy on the Default Environment. However, the app is encountering delegation issues, where it just identifies the impact on the first 2000 flows and is not able to provide analysis on flows beyond 2000. In our landscape, the no. of flows is 4000+ and hence it is causing trouble for us to test impact of DLP policy changes on our landscape. Please help to resolve this issue on priority.

### Expected Behavior

 We should be able to use this tool for more than 2000 apps or flows for Impact analysis to identify the impact of applying a test DLP Policy on the Default Environment. 

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

2.1.7

### What app or flow are you having the issue with?

DLP Editor V2 Canvas app

**Comment by manuelap-msft** [comment]
Hello,

thank you! I'm able to repo this in my demo tenant, and working on hopefully being able to fix this. Will keep you updated through this thread.

Thank you
Manuela

**Comment by JeneferM-MSFT** [comment]
This has been fixed in the latest release 

Please install [the latest version of the toolkit](https://aka.ms/CoEStarterKitDownload) following the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.

**Comment by ALMAcclerator** [comment]
Hello.. We have upgraded to the latest version of COE Kit released in August: Center of Excellence - Core Components Version 2.75. However, we still see the same issue in the DLP Editor app. It does not show "Analyzed Flows" as you highlight in your screenshot above. Please advise.

<img width="745" alt="Capture 2" src="https://user-images.githubusercontent.com/86951487/130613425-e9935320-387c-488d-bd23-106aa06911e5.PNG">
<img width="943" alt="Capture 1" src="https://user-images.githubusercontent.com/86951487/130613430-c59c13c1-216a-414b-9e49-7d72249e77e4.png">

**Comment by JeneferM-MSFT** [comment]
Can you please check to see if you have unmanaged layers on the app? 
We have these in the instructions for [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates). Note that if you do not remove the unmanaged layers as described there you will not receive updates from us.
