### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4 (Custom Connectors) - Failed (item/admin_iconuri - maximum length)

### ISSUE THREAD

**Issue by mmcaak** [microsoft/coe-starter-kit#9748]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

After creating Custom Connectors, then the flow "Admin | Sync Template v4 (Custom Connectors)" fails in 'CreateRecord' with the error:

OpenApiOperationParameterValidationFailed
The 'inputs.parameters' of workflow operation 'Create_Custom_Connector' of type 'OpenApiConnection' is not valid. Error details: The API operation 'CreateRecord' requires the property 'item/admin_iconuri' to be a string of maximum length '500' but is of length '510'.

I am using a standard icon for the the Custom Connector with the URL:
"item/admin_iconuri": "https://pafeblobprodam.blob.core.windows.net/20250325t000000ze0389e268c9a44c887f5d5992befb4f6/aakrpa_aak-20-2d-20custom-20connector-20-2d-20edoc_iconblob.Png?skoid=adaabec0-e03b-41a8-9c91-a97cb4e58635&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2025-03-27T01%3A00%3A00Z&ske=2025-04-03T01%3A00%3A00Z&sks=b&skv=2025-01-05&sv=2025-01-05&spr=https&st=2025-03-27T01%3A05%3A45Z&se=2025-04-01T16%3A00%3A00Z&sr=c&sp=rl&scid=77c68a31-e27a-4da7-a8af-4034db7e6bab&sig=uwHaQHhY%2Be0T%2F6Bs5OEG6Xnr5xbjFqqDCLWVqYvkW0w%3D"

I can verify in the table "admin_connector" table and the field "admin_IconUri" has a limit of 500 signs.

### Expected Behavior

The Custom Connector should be created in the table.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.48.2

### What app or flow are you having the issue with?

Admin | Sync Template v4 (Custom Connectors)

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

I would assume:

1. Create a Custom Connector in an environment.
2. Leave the icon as default
3. Wait for the flow "Admin | Sync Template v4 (Custom Connectors)" to run and fail.

**Comment by mmcaak** [comment]
I have tried to change the limit from 500 to 600 and will see tomorrow if it helped on the flow.

**Comment by pbattini** [comment]
@mmcaak Similar issue logged : https://github.com/microsoft/coe-starter-kit/issues/9699
This has been addressed and will be part of April release.

**Comment by mmcaak** [comment]
I checked today and this still fails even if I raised the limit from 500 to 600. Could it be that it is because the column is a "url" Format type? Or maybe I am missing something?

**Comment by mmcaak** [comment]
Still an issue in april release (CenterofExcellenceCoreComponents_4_48_3_managed.zip) with length 1000 as I see it.

**Comment by sabineFPSFA** [comment]
Apparently still an issue in the August release (CoE Core Component 4.50.3)?
