### ISSUE TITLE
[CoE Starter Kit - BUG] Admin | Sync Template v4(Custom Connectors) failing

### ISSUE THREAD

**Issue by chiragknzariya** [microsoft/coe-starter-kit#9820]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

Hello,

Admin | Sync Template v4(Custom Connectors) is failing because admin_iconuri field has 500 character limit.

### What solution are you experiencing the issue with?

Core

### What solution version are you using?

4.23

### What app or flow are you having the issue with?

Admin | Sync Template v4(Custom Connectors)

### What method are you using to get inventory and telemetry?

Cloud flows

**Comment by pbattini** [comment]
@chiragknzariya Similar issue [#9699](https://github.com/microsoft/coe-starter-kit/issues/9699).

This has been fixed in April release.

**Comment by mmcaak** [comment]
Still an issue in april release (CenterofExcellenceCoreComponents_4_48_3_managed.zip) with length 1000 as I see it.

**Comment by Kennerss** [comment]
Hello, 
I'm getting this when the "Admin | Sync Template v4 (Custom Connectors)" flow is run, 

It started on the 29th April.   shall i raise a new bug, or will it be ok here?   Thanks

I searched for the Environment( the question marks) , but it it doesnt exist.

Action 'Get_Custom_Connectors_as_Admin' failed: The user with object id '***************************' in tenant '***********************************' does not have access to permission 'ManageAnyCustomApi' in environment '??????????????????????????????'. Error Code: '<null>'

**Comment by RajeevPentyala** [comment]
@mmcaak Can you please log a new issue with the exception details you were getting? Please note that the length of the field has already been increased to 2000 characters.
@Kennerss Please log new ticket as the issue you are facing is different.

**Comment by RajeevPentyala** [comment]
@chiragknzariya Closing this ticket as there is no further action needed from COE Kit team. Please reach out if you need further assistance.
