### ISSUE TITLE
[CoE Starter Kit - BUG] Unexpected Email Flood (Quarantine release) triggered by Fix for Issue #9637

### ISSUE THREAD

**Issue by Louicha** [microsoft/coe-starter-kit#9983]
### Does this bug already exist in our backlog?

- [x] I have checked and confirm this is a new bug.

### Describe the issue

By resolving issue [#9637 Quarantine App Not Set Since 4.47.1 ](https://github.com/microsoft/coe-starter-kit/issues/9637) the "Admin | Set app quarantine status" flow is now sending out countless emails stating that an app has been released from quarantine (Send an email - release). Emails were also sent for the apps and SharePoint forms in the default environment. The default environment is excluded from quarantine in our setup (Excuse from Quarantine =Yes)!!

In the resolution of issue #9637 , it is likely that the quarantine status is being set to false in the "SYNC HELPER - Apps" flow.
Since the field  "admin_appisquarantined" was probably empty before, the "Admin | Set app quarantine status" flow is now triggered and sends out emails because the value of admin_appisquarantined is now set to false.

### Expected Behavior

When a new default value is written into a field, it’s important to consider which other flows are connected to it and which processes might be triggered as a result.
Normally, users should only receive this email if an app has actually been released from quarantine.
In this case, however, none of the apps were previously in quarantine

### What solution are you experiencing the issue with?

Governance

### What solution version are you using?

3.27.2

### What app or flow are you having the issue with?

Admin | Set app quarantine status

### What method are you using to get inventory and telemetry?

Cloud flows

### Steps To Reproduce

Install the June 25 Release for core components and governance components.

### Anything else?

The issue was triggered by the June 25 Release.

**Comment by RajeevPentyala** [comment]
@Louicha We will reproduce the issue and provide a fix if necessary.

**Comment by TiBa7879** [comment]
I have the same problem, after installing the June update yesterday. 
Can you please confirm, that these emails will only be send out once (until the admin_appisquarantined value is set)? Or do I have to change/stop something manually to avoid these emails on next run?
Thank you very much.

**Comment by PokkeDEV** [comment]
We got the same Issue. It is because the Flow "SYNC HELPER - Apps" is modifying the quarantine state which triggers this flow "Admin | Set app quarantine status", which only has two options, release or quarantine.

**Comment by sklincov** [comment]
We have the Same Issue / Problem as well. Is there any information on this on how to fix it ? or maybe the value has to be Excluced "YES", before the update is taking place ? or is it the other way around ?

**Comment by MshulerIWT** [comment]
We are also experiencing the same issue after applying the August 2025 updated.
Any update on a resolution to stop the "Your app has been released from quarantine" emails?

**Comment by yhaugom** [comment]
We see the same thing and disabled the flow that sends out the emails until a fix is available.

**Comment by Louicha** [comment]
Is there already a solution for this? We haven't dared to reactivate the flow yet, as we don't want to trigger another email flood.

I saw that there is another issue related to this problem, but it was simply closed without being answered. #9791

**Comment by MartinWGT** [comment]
I raised this too #10242 but am still not sure about the fix and if there should be an update to CoE itself which there hasn't as far as I can see.

**Comment by Gnosynthesis** [comment]
I wonder why there are two quarantine columns in the dataverse powerapps app table - admin_appisquarantined and admin_quarantineapp, both are yes/no fields, using the flow action Power Apps for Admins/Set App Quarantine State updates the column admin_appisquarantined to yes and adds the date to the field admin_quarantineappdate, but does not adjust the field admin_quarantineapp, however in the Power Platform Admin View, this column needs to be marked as Yes in order to appear under the Quarantine Canvas App view...this is just one disconnect that I discovered going down the quarantine rabbit hole...so why is the PPAV is pointing to one field and the automation is pointing at another?

<img width="1212" height="523" alt="Image" src="https://github.com/user-attachments/assets/9d1c8a41-df60-4efe-b69a-26ce794ca2df" />

**Comment by yhaugom** [comment]
Same here. Still waiting for a fix before activating. This is to me a pretty "critical" bug since it spams employees with false information regularly.

**Comment by yhaugom** [comment]
Why do you keep pushing this? Are there a resolution to it or a workaround? I don't understand why not more users have this issue otherwise, since it is clearly not a priority‽

**Comment by yhaugom** [comment]
@RajeevPentyala – please respond. Is this not a bug, or what exactly is being done here?
There’s been silence since June…

**Comment by PokkeDEV** [comment]
Any news for this issue?! This issues is open since june 2025 and mentioned in several tickets. Nearly every ticket closed because of "no informations" from user. 

One Example: https://github.com/microsoft/coe-starter-kit/issues/9791

Can you please fix this issue it is very important to have this feature active!
